project_id = "xxtjzhgayiqehnabxgnl"

[functions.send-review-requests]
verify_jwt = false

[functions.track-open]
verify_jwt = false

[functions.track-click]
verify_jwt = false

[functions.review-landing]
verify_jwt = false

[functions.feedback-data]
verify_jwt = false


[functions.process-sequence]
verify_jwt = false

[functions.send-demo-email]
verify_jwt = false

[functions.lemon-webhook]
verify_jwt = false
